### ISSUE TITLE
Cannot use the commands in Skype

### ISSUE THREAD

**Issue by maxklock** [Herb1/MensaBot#1]
When I try to use one of the commands in skype, I'm just getting the following message:

```
Available commands:
 /me [text]
 /add [skypename+]
 /alertson [text]
 /alertsoff
 /wikimarkup
 /help
For more help please see http://www.skype.com/go/help.chathelp
```

**Comment by Herb1** [comment]
You can just ignore / and use the same commands as in telegram.

I will add a better help later. I promise :)
